package com.zrzyyzt.runtimeviewer.BMOD.PhotoModule;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.zrzyyzt.runtimeviewer.Entity.PhotoEntity;

import com.zrzyyzt.runtimeviewer.BMOD.PhotoModule.PhotoEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig photoEntityDaoConfig;

    private final PhotoEntityDao photoEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        photoEntityDaoConfig = daoConfigMap.get(PhotoEntityDao.class).clone();
        photoEntityDaoConfig.initIdentityScope(type);

        photoEntityDao = new PhotoEntityDao(photoEntityDaoConfig, this);

        registerDao(PhotoEntity.class, photoEntityDao);
    }
    
    public void clear() {
        photoEntityDaoConfig.clearIdentityScope();
    }

    public PhotoEntityDao getPhotoEntityDao() {
        return photoEntityDao;
    }

}
